<a href="https://colab.research.google.com/github/sun226/AI2/blob/main/13~20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def print_val(X):
    print ("Type:" , type (X))
    print ("Shape:" , X.shape )
    print ("값 :\n" , X)
    print (" ")
  

In [ ]:
X = np.array ([1, 2, 3])
print_val (X)

X[0] = 5
print_val (X)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값 :
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값 :
 [5 2 3]
 


In [ ]:
y = np.array([[1,2,3],[4,5,6]])
print_val(y)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값 :
 [[1 2 3]
 [4 5 6]]
 


In [ ]:
a = np.zeros((2,2))
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[0. 0.]
 [0. 0.]]
 


In [ ]:
a = np.ones((3,2))
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값 :
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


In [ ]:
a = np.eye(3,3)
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값 :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


In [ ]:
a = np.random.random((4,4))
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값 :
 [[0.61938552 0.45142491 0.75060205 0.7158796 ]
 [0.22975194 0.43527571 0.31653127 0.89073257]
 [0.33558077 0.97745311 0.91416373 0.17802384]
 [0.56045124 0.0206189  0.6147535  0.09853933]]
 


In [ ]:
a = np.random.randn(4,4)
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값 :
 [[-0.79109289 -0.38617725 -1.32821506  0.24954276]
 [ 1.1072601   0.33147517 -0.80585659 -0.70978367]
 [-2.03748015  1.555404    0.08698578 -2.7376934 ]
 [ 0.08376618 -1.14826132 -0.23381884 -1.07392046]]
 


In [ ]:
a = np.array([[1,2,3,4,], [5,6,7,8], [9,10,11,12]])
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (3, 4)
값 :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 


In [ ]:
b = a[:2, 1:3]
print_val (b)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[2 3]
 [6 7]]
 


In [ ]:
row1 = a[1, :]
print_val (row1)

Type: <class 'numpy.ndarray'>
Shape: (4,)
값 :
 [5 6 7 8]
 


In [ ]:
m1 = np.array([[1,2], [3,4]], dtype=np.float64)
m2 = np.array([[5,6], [7,8]], dtype=np.float64)

In [ ]:
print_val(m1 + m2)
print_val(np.add(m1, m2))

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[ 6.  8.]
 [10. 12.]]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[ 6.  8.]
 [10. 12.]]
 


In [ ]:
print_val(m1 - m2)
print_val(np.subtract(m1, m2))

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[-4. -4.]
 [-4. -4.]]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[-4. -4.]
 [-4. -4.]]
 


In [ ]:
print_val(m1 * m2)
print_val(np.multiply(m1, m2))

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[ 5. 12.]
 [21. 32.]]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[ 5. 12.]
 [21. 32.]]
 


In [ ]:
print_val(m1 / m2)
print_val(np.divide(m1, m2))

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 


In [ ]:
print_val(np.sqrt(m1))

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값 :
 [[1.         1.41421356]
 [1.73205081 2.        ]]
 
